apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Flask-App-EKS-Cluster-VPC
  region: us-east-1

vpc:
  id: vpc-04c88dd384b2fe99d
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0b5129dc8fe9d3a30
      us-east-1b:
        id: subnet-0e7aa70837c478f68
    private:
      us-east-1a:
        id: subnet-036b2d671d8756538
      us-east-1b:
        id: subnet-0f36c70ac8b589384

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true