apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: flask-api-back-end
          image: 014129292631.dkr.ecr.us-east-1.amazonaws.com/flaskmicroservice:latest
          ports:
            - containerPort: 80